// 信越エリア路線データ
window.railwayLinesDataChunks = window.railwayLinesDataChunks || {};
Object.assign(window.railwayLinesDataChunks, {
  "shinetsu:uetsu": { area: "信越", lineName: "羽越本線", scope: "新潟支社", stations: [{ name: "新津" }, { name: "京ケ瀬" }, { name: "水原" }, { name: "神山" }, { name: "月岡" }, { name: "中浦" }, { name: "新発田" }, { name: "加治" }, { name: "金塚" }, { name: "中条" }, { name: "平木田" }, { name: "坂町" }, { name: "平林" }, { name: "岩船町" }, { name: "村上" }] },
  "shinetsu:shinetsu_main": { area: "信越", lineName: "信越本線", scope: "新潟支社", stations: [{ name: "直江津" }, { name: "黒井" }, { name: "犀潟" }, { name: "土底浜" }, { name: "潟町" }, { name: "上下浜" }, { name: "柿崎" }, { name: "米山" }, { name: "笠島" }, { name: "青海川" }, { name: "鯨波" }, { name: "柏崎" }, { name: "茨目" }, { name: "安田" }, { name: "北条" }, { name: "越後広田" }, { name: "長鳥" }, { name: "塚山" }, { name: "越後岩塚" }, { name: "来迎寺" }, { name: "前川" }, { name: "宮内" }, { name: "長岡" }, { name: "北長岡" }, { name: "押切" }, { name: "見附" }, { name: "帯織" }, { name: "東光寺" }, { name: "三条" }, { name: "東三条" }, { name: "保内" }, { name: "加茂" }, { name: "羽生田" }, { name: "田上" }, { name: "矢代田" }, { name: "古津" }, { name: "新津" }, { name: "さつき野" }, { name: "荻川" }, { name: "亀田" }, { name: "越後石山" }, { name: "新潟" }] },
  "shinetsu:shinetsu_main_nagano": { area: "信越", lineName: "信越本線", scope: "長野支社", stations: [{ name: "篠ノ井" }, { name: "今井" }, { name: "川中島" }, { name: "安茂里" }, { name: "長野" }] },
  "shinetsu:joetsu": { area: "信越", lineName: "上越線", scope: "新潟支社", stations: [{ name: "水上" }, { name: "湯檜曽" }, { name: "土合" }, { name: "土樽" }, { name: "越後中里" }, { name: "岩原スキー場前" }, { name: "越後湯沢" }, { name: "石打" }, { name: "大沢" }, { name: "上越国際スキー場前" }, { name: "塩沢" }, { name: "六日町" }, { name: "五日町" }, { name: "浦佐" }, { name: "八色" }, { name: "小出" }, { name: "越後堀之内" }, { name: "北堀之内" }, { name: "越後川口" }, { name: "小千谷" }, { name: "越後滝谷" }, { name: "宮内" }] },
  "shinetsu:shinonoi": { area: "信越", lineName: "篠ノ井線", scope: "長野支社", stations: [{ name: "篠ノ井" }, { name: "稲荷山" }, { name: "姨捨" }, { name: "聖高原" }, { name: "冠着" }, { name: "坂北" }, { name: "西条" }, { name: "明科" }, { name: "田沢" }, { name: "松本" }, { name: "南松本" }, { name: "平田" }, { name: "村井" }, { name: "広丘" }, { name: "塩尻" }] },
  "shinetsu:koshinetsu_chuo_main": { area: "信越", lineName: "中央本線", scope: "長野支社", stations: [{ name: "塩尻" }, { name: "みどり湖" }, { name: "川岸" }, { name: "岡谷" }, { name: "下諏訪" }, { name: "上諏訪" }, { name: "茅野" }, { name: "青柳" }, { name: "すずらんの里" }, { name: "富士見" }, { name: "信濃境" }, { name: "小淵沢" }] },
  "shinetsu:koshinetsu_chuo_main_via_tatsuno": { area: "信越", lineName: "中央本線", scope: "辰野経由", stations: [{ name: "岡谷" }, { name: "川岸" }, { name: "辰野" }, { name: "信濃川島" }, { name: "小野" }, { name: "塩尻" }] },
  "shinetsu:hakushin": { area: "信越", lineName: "白新線", scope: "新潟支社", stations: [{ name: "新潟" }, { name: "東新潟" }, { name: "大形" }, { name: "新崎" }, { name: "早通" }, { name: "豊栄" }, { name: "黒山" }, { name: "佐々木" }, { name: "西新発田" }, { name: "新発田" }] },
  "shinetsu:banetsu_west": { area: "信越", lineName: "磐越西線", scope: "新潟支社", stations: [{ name: "五泉" }, { name: "猿和田" }, { name: "馬下" }, { name: "咲花" }, { name: "東下条" }, { name: "新関" }, { name: "北五泉" }, { name: "新津" }] },
  "shinetsu:iiyama": { area: "信越", lineName: "飯山線", scope: "長野支社", stations: [{ name: "豊野" }, { name: "信濃浅野" }, { name: "立ケ花" }, { name: "上今井" }, { name: "替佐" }, { name: "蓮" }, { name: "飯山" }, { name: "北飯山" }, { name: "信濃平" }, { name: "戸狩野沢温泉" }, { name: "上境" }, { name: "上桑名川" }, { name: "桑名川" }, { name: "西大滝" }, { name: "森宮野原" }, { name: "足滝" }, { name: "越後田中" }, { name: "津南" }, { name: "越後鹿渡" }, { name: "越後田沢" }, { name: "越後水沢" }, { name: "土市" }, { name: "十日町" }, { name: "魚沼中条" }, { name: "下条" }, { name: "越後岩沢" }, { name: "内ケ巻" }, { name: "越後川口" }] },
  "shinetsu:echigo": { area: "信越", lineName: "越後線", scope: "新潟支社", stations: [{ name: "柏崎" }, { name: "東柏崎" }, { name: "西中通" }, { name: "荒浜" }, { name: "刈羽" }, { name: "西山" }, { name: "礼拝" }, { name: "石地" }, { name: "小木ノ城" }, { name: "出雲崎" }, { name: "妙法寺" }, { name: "小島谷" }, { name: "桐原" }, { name: "寺泊" }, { name: "分水" }, { name: "粟生津" }, { name: "南吉田" }, { name: "吉田" }, { name: "北吉田" }, { name: "岩室" }, { name: "巻" }, { name: "越後曽根" }, { name: "越後赤塚" }, { name: "内野西が丘" }, { name: "内野" }, { name: "新潟大学前" }, { name: "寺尾" }, { name: "小針" }, { name: "青山" }, { name: "関屋" }, { name: "白山" }, { name: "新潟" }] },
  "shinetsu:oito": { area: "信越", lineName: "大糸線", scope: "長野支社", stations: [{ name: "松本" }, { name: "北松本" }, { name: "島内" }, { name: "島高松" }, { name: "梓橋" }, { name: "一日市場" }, { name: "中萱" }, { name: "南豊科" }, { name: "豊科" }, { name: "柏矢町" }, { name: "穂高" }, { name: "有明" }, { name: "安曇追分" }, { name: "細野" }, { name: "北細野" }, { name: "信濃松川" }, { name: "安曇沓掛" }, { name: "信濃常盤" }, { name: "南大町" }, { name: "信濃大町" }, { name: "北大町" }, { name: "白馬" }, { name: "南小谷" }] },
  "shinetsu:koumi": { area: "信越", lineName: "小海線", scope: "長野支社", stations: [{ name: "小淵沢" }, { name: "甲斐小泉" }, { name: "甲斐大泉" }, { name: "清里" }, { name: "野辺山" }, { name: "信濃川上" }, { name: "佐久広瀬" }, { name: "佐久海ノ口" }, { name: "海尻" }, { name: "松原湖" }, { name: "小海" }, { name: "馬流" }, { name: "高岩" }, { name: "八千穂" }, { name: "海瀬" }, { name: "羽黒下" }, { name: "青沼" }, { name: "臼田" }, { name: "龍岡城" }, { name: "太田部" }, { name: "中込" }, { name: "滑津" }, { name: "北中込" }, { name: "岩村田" }, { name: "佐久平" }, { name: "中佐都" }, { name: "美里" }, { name: "三岡" }, { name: "乙女" }, { name: "東小諸" }, { name: "小諸" }] },
  "shinetsu:tadami": { area: "信越", lineName: "只見線", scope: "福島・新潟支社", stations: [{ name: "会津若松" }, { name: "七日町" }, { name: "西若松" }, { name: "会津本郷" }, { name: "会津高田" }, { name: "根岸" }, { name: "新鶴" }, { name: "若宮" }, { name: "会津坂下" }, { name: "塔寺" }, { name: "会津柳津" }, { name: "郷戸" }, { name: "滝谷" }, { name: "会津桧原" }, { name: "会津西方" }, { name: "会津宮下" }, { name: "早戸" }, { name: "会津水沼" }, { name: "会津中川" }, { name: "会津川口" }, { name: "本名" }, { name: "会津越川" }, { name: "会津横田" }, { name: "会津大塩" }, { name: "会津塩沢" }, { name: "会津蒲生" }, { name: "只見" }, { name: "大白川" }, { name: "入広瀬" }, { name: "上条" }, { name: "越後須原" }, { name: "魚沼田中" }, { name: "越後広瀬" }, { name: "藪神" }, { name: "小出" }] },
  "shinetsu:yahiko": { area: "信越", lineName: "弥彦線", scope: "新潟支社", stations: [{ name: "弥彦" }, { name: "矢作" }, { name: "吉田" }, { name: "西燕" }, { name: "燕" }, { name: "燕三条" }, { name: "北三条" }, { name: "東三条" }] },
  "shinetsu:yonesaka": { area: "信越", lineName: "米坂線", scope: "新潟支社", stations: [{ name: "坂町" }, { name: "越後下関" }, { name: "越後片貝" }, { name: "越後金丸" }, { name: "小国" }, { name: "羽前松岡" }, { name: "手ノ子" }, { name: "羽前沼沢" }, { name: "伊佐領" }, { name: "羽前椿" }, { name: "萩生" }, { name: "米沢" }] }
});
