// 東北エリア路線データ
window.railwayLinesDataChunks = window.railwayLinesDataChunks || {};
Object.assign(window.railwayLinesDataChunks, {
  "tohoku:uetsu_northern": { area: "東北", lineName: "羽越本線", scope: "秋田・酒田側", stations: [{ name: "秋田" }, { name: "羽後本荘" }, { name: "仁賀保" }, { name: "酒田" }] },
  "tohoku:ou_main_aomori_akita": { area: "東北", lineName: "奥羽本線", scope: "青森・秋田", stations: [{ name: "青森" }, { name: "弘前" }, { name: "大館" }, { name: "鷹ノ巣" }, { name: "秋田" }] },
  "tohoku:ou_main_yamagata": { area: "東北", lineName: "奥羽本線", scope: "山形線", stations: [{ name: "福島" }, { name: "米沢" }, { name: "高畠" }, { name: "赤湯" }, { name: "かみのやま温泉" }, { name: "山形" }, { name: "天童" }, { name: "新庄" }] },
  "tohoku:joban": { area: "東北", lineName: "常磐線", scope: "仙台支社", stations: [{ name: "いわき" }, { name: "原ノ町" }, { name: "相馬" }, { name: "亘理" }, { name: "岩沼" }, { name: "仙台" }] },
  "tohoku:senzan": { area: "東北", lineName: "仙山線", scope: "仙台支社", stations: [{ name: "仙台" }, { name: "奥新川" }, { name: "面白山高原" }, { name: "山寺" }, { name: "山形" }] },
  "tohoku:senseki": { area: "東北", lineName: "仙石線", scope: "仙台支社", stations: [{ name: "あおば通" }, { name: "仙台" }, { name: "本塩釜" }, { name: "松島海岸" }, { name: "高城町" }, { name: "石巻" }] },
  "tohoku:senseki_tohoku": { area: "東北", lineName: "仙石東北ライン", scope: "仙台支社", stations: [{ name: "仙台" }, { name: "塩釜" }, { name: "高城町" }, { name: "石巻" }] },
  "tohoku:tohoku_main": { area: "東北", lineName: "東北本線", scope: "盛岡支社", stations: [{ name: "仙台" }, { name: "松島" }, { name: "小牛田" }, { name: "一ノ関" }, { name: "北上" }, { name: "花巻" }, { name: "盛岡" }] },
  "tohoku:banetsu_west": { area: "東北", lineName: "磐越西線", scope: "会津側", stations: [{ name: "郡山" }, { name: "磐梯熱海" }, { name: "猪苗代" }, { name: "会津若松" }, { name: "野沢" }, { name: "日出谷" }, { name: "荻野" }] },
  "tohoku:aterazawa": { area: "東北", lineName: "左沢線", scope: "山形支社", stations: [{ name: "山形" }, { name: "寒河江" }, { name: "左沢" }] },
  "tohoku:ishinomaki": { area: "東北", lineName: "石巻線", scope: "仙台支社", stations: [{ name: "小牛田" }, { name: "前谷地" }, { name: "石巻" }, { name: "女川" }] },
  "tohoku:ofunato": { area: "東北", lineName: "大船渡線", scope: "盛岡支社", stations: [{ name: "一ノ関" }, { name: "気仙沼" }, { name: "盛" }] },
  "tohoku:ofunato_brt": { area: "東北", lineName: "大船渡線ＢＲＴ", scope: "BRT", stations: [{ name: "気仙沼" }, { name: "陸前高田" }, { name: "盛" }] },
  "tohoku:omminato": { area: "東北", lineName: "大湊線", scope: "盛岡支社", stations: [{ name: "野辺地" }, { name: "下北" }, { name: "大湊" }] },
  "tohoku:oga": { area: "東北", lineName: "男鹿線", scope: "秋田支社", stations: [{ name: "秋田" }, { name: "追分" }, { name: "男鹿" }] },
  "tohoku:kamaishi": { area: "東北", lineName: "釜石線", scope: "盛岡支社", stations: [{ name: "花巻" }, { name: "遠野" }, { name: "釜石" }] },
  "tohoku:kitakami": { area: "東北", lineName: "北上線", scope: "盛岡支社", stations: [{ name: "北上" }, { name: "ほっとゆだ" }, { name: "横手" }] },
  "tohoku:kesennuma": { area: "東北", lineName: "気仙沼線", scope: "仙台支社", stations: [{ name: "小牛田" }, { name: "前谷地" }, { name: "柳津" }, { name: "気仙沼" }] },
  "tohoku:kesennuma_brt": { area: "東北", lineName: "気仙沼線ＢＲＴ", scope: "BRT", stations: [{ name: "柳津" }, { name: "陸前戸倉" }, { name: "清水浜" }, { name: "歌津" }, { name: "気仙沼" }] },
  "tohoku:gono": { area: "東北", lineName: "五能線", scope: "秋田支社", stations: [{ name: "能代" }, { name: "東能代" }, { name: "深浦" }, { name: "鰺ケ沢" }, { name: "五所川原" }, { name: "陸奥鶴田" }, { name: "弘前" }] },
  "tohoku:suigun": { area: "東北", lineName: "水郡線", scope: "水戸支社", stations: [{ name: "水戸" }, { name: "常陸大子" }, { name: "郡山" }] },
  "tohoku:tazawako": { area: "東北", lineName: "田沢湖線", scope: "秋田支社", stations: [{ name: "盛岡" }, { name: "雫石" }, { name: "田沢湖" }, { name: "角館" }, { name: "大曲" }] },
  "tohoku:tadami": { area: "東北", lineName: "只見線", scope: "東北本部", stations: [{ name: "会津若松" }, { name: "会津坂下" }, { name: "会津川口" }, { name: "只見" }, { name: "大白川" }, { name: "小出" }] },
  "tohoku:tsugaru": { area: "東北", lineName: "津軽線", scope: "盛岡支社", stations: [{ name: "青森" }, { name: "蟹田" }, { name: "三厩" }] },
  "tohoku:hachinohe": { area: "東北", lineName: "八戸線", scope: "盛岡支社", stations: [{ name: "八戸" }, { name: "鮫" }, { name: "久慈" }] },
  "tohoku:hanawa": { area: "東北", lineName: "花輪線", scope: "盛岡支社", stations: [{ name: "好摩" }, { name: "荒屋新町" }, { name: "鹿角花輪" }, { name: "大館" }] },
  "tohoku:banetsu_east": { area: "東北", lineName: "磐越東線", scope: "仙台支社", stations: [{ name: "いわき" }, { name: "小野新町" }, { name: "船引" }, { name: "郡山" }] },
  "tohoku:yamada": { area: "東北", lineName: "山田線", scope: "盛岡支社", stations: [{ name: "盛岡" }, { name: "茂市" }, { name: "宮古" }] },
  "tohoku:yonesaka": { area: "東北", lineName: "米坂線", scope: "山形支社", stations: [{ name: "坂町" }, { name: "小国" }, { name: "今泉" }, { name: "米沢" }] },
  "tohoku:rikuu_west": { area: "東北", lineName: "陸羽西線", scope: "山形支社", stations: [{ name: "新庄" }, { name: "余目" }] },
  "tohoku:rikuu_east": { area: "東北", lineName: "陸羽東線", scope: "仙台支社", stations: [{ name: "小牛田" }, { name: "古川" }, { name: "鳴子温泉" }, { name: "新庄" }] }
});
