// 山手線系メタデータ
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "東京": { nameKana: "とうきょう", interchanges: [{ toOperator: "JR東日本", toLine: "各線" }, { toOperator: "東京メトロ", toLine: "丸ノ内線" }] },
  "有楽町": { nameKana: "ゆうらくちょう", interchanges: [{ toOperator: "東京メトロ", toLine: "有楽町線" }, { toOperator: "東京メトロ", toLine: "日比谷線" }] },
  "新橋": { nameKana: "しんばし", interchanges: [{ toOperator: "JR東日本", toLine: "東海道線" }, { toOperator: "JR東日本", toLine: "横須賀線" }, { toOperator: "東京メトロ", toLine: "銀座線" }, { toOperator: "都営", toLine: "浅草線" }] },
  "浜松町": { nameKana: "はままつちょう", interchanges: [{ toOperator: "東京モノレール", toLine: "東京モノレール線" }] },
  "田町": { nameKana: "たまち", interchanges: [{ toOperator: "都営", toLine: "浅草線", toStationName: "三田駅" }] },
  "高輪ゲートウェイ": { nameKana: "たかなわげーとうぇい" },
  "品川": { nameKana: "しながわ", interchanges: [{ toOperator: "JR東日本", toLine: "東海道線" }, { toOperator: "JR東日本", toLine: "横須賀線" }, { toOperator: "JR東日本", toLine: "京浜東北線" }, { toOperator: "京急", toLine: "本線" }] },
  "大崎": { nameKana: "おおさき", interchanges: [{ toOperator: "JR東日本", toLine: "埼京線" }, { toOperator: "JR東日本", toLine: "湘南新宿ライン" }, { toOperator: "東京臨海高速鉄道", toLine: "りんかい線" }] },
  "五反田": { nameKana: "ごたんだ", interchanges: [{ toOperator: "東急", toLine: "池上線" }, { toOperator: "都営", toLine: "浅草線" }] },
  "目黒": { nameKana: "めぐろ", interchanges: [{ toOperator: "東急", toLine: "目黒線" }, { toOperator: "東京メトロ", toLine: "南北線" }, { toOperator: "都営", toLine: "三田線" }] },
  "恵比寿": { nameKana: "えびす", interchanges: [{ toOperator: "JR東日本", toLine: "湘南新宿ライン" }, { toOperator: "東京メトロ", toLine: "日比谷線" }] },
  "渋谷": { nameKana: "しぶや", interchanges: [{ toOperator: "JR東日本", toLine: "埼京線" }, { toOperator: "JR東日本", toLine: "湘南新宿ライン" }, { toOperator: "東急", toLine: "東横線ほか多数" }] },
  "原宿": { nameKana: "はらじゅく", interchanges: [{ toOperator: "東京メトロ", toLine: "千代田線", toStationName: "明治神宮前" }, { toOperator: "東京メトロ", toLine: "副都心線", toStationName: "明治神宮前" }] },
  "代々木": { nameKana: "よよぎ", interchanges: [{ toOperator: "JR東日本", toLine: "中央・総武緩行線" }, { toOperator: "都営", toLine: "大江戸線" }] },
  "新宿": { nameKana: "しんじゅく", interchanges: [{ toOperator: "JR東日本", toLine: "中央線" }, { toOperator: "JR東日本", toLine: "埼京線ほか" }, { toOperator: "京王電鉄", toLine: "京王線" }, { toOperator: "小田急電鉄", toLine: "小田原線" }, { toOperator: "東京メトロ", toLine: "地下鉄多数" }] },
  "新大久保": { nameKana: "しんおおくぼ" },
  "高田馬場": { nameKana: "たかだのばば", interchanges: [{ toOperator: "西武鉄道", toLine: "新宿線" }, { toOperator: "東京メトロ", toLine: "東西線" }] },
  "目白": { nameKana: "めじろ" },
  "池袋": { nameKana: "いけぶくろ", interchanges: [{ toOperator: "東武鉄道", toLine: "東上線" }, { toOperator: "西武鉄道", toLine: "池袋線" }, { toOperator: "東京メトロ", toLine: "各線" }] },
  "大塚": { nameKana: "おおつか", interchanges: [{ toOperator: "都電荒川線", toLine: "東京さくらトラム" }] },
  "巣鴨": { nameKana: "すがも", interchanges: [{ toOperator: "都営", toLine: "三田線" }] },
  "駒込": { nameKana: "こまごめ", interchanges: [{ toOperator: "東京メトロ", toLine: "南北線" }] },
  "田端": { nameKana: "たばた", interchanges: [{ toOperator: "JR東日本", toLine: "京浜東北線" }] },
  "西日暮里": { nameKana: "にしにっぽり", interchanges: [{ toOperator: "京成電鉄", toLine: "本線" }, { toOperator: "東京メトロ", toLine: "千代田線" }] },
  "日暮里": { nameKana: "にっぽり", interchanges: [{ toOperator: "京成電鉄", toLine: "本線" }, { toOperator: "日暮里・舎人ライナー", toLine: "日暮里・舎人ライナー" }] },
  "鶯谷": { nameKana: "うぐいすだに" },
  "上野": { nameKana: "うえの", interchanges: [{ toOperator: "JR東日本", toLine: "高崎線" }, { toOperator: "JR東日本", toLine: "宇都宮線ほか" }, { toOperator: "東京メトロ", toLine: "銀座線" }, { toOperator: "東京メトロ", toLine: "日比谷線" }] },
  "御徒町": { nameKana: "おかちまち", interchanges: [{ toOperator: "東京メトロ", toLine: "銀座線", toStationName: "上野広小路" }, { toOperator: "他路線", toLine: "ほか" }] },
  "秋葉原": { nameKana: "あきはばら", interchanges: [{ toOperator: "JR東日本", toLine: "総武線" }, { toOperator: "東京メトロ", toLine: "日比谷線" }, { toOperator: "つくばエクスプレス", toLine: "つくばエクスプレス" }] },
  "神田": { nameKana: "かんだ", interchanges: [{ toOperator: "JR東日本", toLine: "中央線" }, { toOperator: "JR東日本", toLine: "京浜東北線" }, { toOperator: "東京メトロ", toLine: "銀座線" }] }
});

