// 東海道方面メタデータ（東海道線/京浜東北線/横須賀線/南武線/横浜線/伊東線/相模線/鶴見線）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "大宮": { nameKana: "おおみや", interchanges: [{ toOperator: "東武", toLine: "野田線" }, { toOperator: "埼玉新都市交通", toLine: "伊奈線" }] },
  "さいたま新都心": { nameKana: "さいたましんとしん" },
  "与野": { nameKana: "よの" },
  "北浦和": { nameKana: "きたうらわ" },
  "浦和": { nameKana: "うらわ" },
  "南浦和": { nameKana: "みなみうらわ" },
  "蕨": { nameKana: "わらび" },
  "西川口": { nameKana: "にしかわぐち" },
  "川口": { nameKana: "かわぐち" },
  "赤羽": { nameKana: "あかばね" },
  "東十条": { nameKana: "ひがしじゅうじょう" },
  "王子": { nameKana: "おうじ", interchanges: [{ toOperator: "東京メトロ", toLine: "南北線" }, { toOperator: "都電", toLine: "荒川線", toStationName: "王子駅前" }] },
  "上中里": { nameKana: "かみなかざと" },
  "田端": { nameKana: "たばた" },
  "西日暮里": { nameKana: "にしにっぽり", interchanges: [{ toOperator: "東京メトロ", toLine: "千代田線" }] },
  "日暮里": { nameKana: "にっぽり", interchanges: [{ toOperator: "京成", toLine: "本線" }] },
  "鶯谷": { nameKana: "うぐいすだに" },
  "上野": { nameKana: "うえの", interchanges: [{ toOperator: "東京メトロ", toLine: "銀座線" }, { toOperator: "東京メトロ", toLine: "日比谷線" }] },
  "御徒町": { nameKana: "おかちまち", interchanges: [{ toOperator: "東京メトロ", toLine: "日比谷線", toStationName: "仲御徒町" }] },
  "秋葉原": { nameKana: "あきはばら", interchanges: [{ toOperator: "東京メトロ", toLine: "日比谷線" }, { toOperator: "つくばエクスプレス", toLine: "常磐新線" }] },
  "神田": { nameKana: "かんだ", interchanges: [{ toOperator: "東京メトロ", toLine: "銀座線" }] },
  "東京": { nameKana: "とうきょう", interchanges: [{ toOperator: "東京メトロ", toLine: "丸ノ内線" }] },
  "有楽町": { nameKana: "ゆうらくちょう", interchanges: [{ toOperator: "東京メトロ", toLine: "有楽町線" }] },
  "新橋": { nameKana: "しんばし", interchanges: [{ toOperator: "都営", toLine: "浅草線" }, { toOperator: "東京メトロ", toLine: "銀座線" }, { toOperator: "ゆりかもめ", toLine: "東京臨海新交通臨海線" }] },
  "浜松町": { nameKana: "はままつちょう", interchanges: [{ toOperator: "東京モノレール", toLine: "東京モノレール羽田空港線" }, { toOperator: "都営", toLine: "大江戸線", toStationName: "大門" }, { toOperator: "都営", toLine: "浅草線", toStationName: "大門" }] },
  "田町": { nameKana: "たまち", interchanges: [{ toOperator: "都営", toLine: "浅草線", toStationName: "三田" }, { toOperator: "都営", toLine: "三田線", toStationName: "三田" }] },
  "高輪ゲートウェイ": { nameKana: "たかなわげーとうぇい" },
  "品川": { nameKana: "しながわ", interchanges: [{ toOperator: "京急", toLine: "本線" }] },
  "大井町": { nameKana: "おおいまち", interchanges: [{ toOperator: "東急", toLine: "大井町線" }, { toOperator: "東京臨海高速鉄道", toLine: "りんかい線" }] },
  "大森": { nameKana: "おおもり" },
  "蒲田": { nameKana: "かまた", interchanges: [{ toOperator: "東急", toLine: "池上線" }, { toOperator: "東急", toLine: "多摩川線" }] },
  "川崎": { nameKana: "かわさき", interchanges: [{ toOperator: "京急", toLine: "本線", toStationName: "京急川崎" }] },
  "鶴見": { nameKana: "つるみ", interchanges: [{ toOperator: "京急", toLine: "本線", toStationName: "京急鶴見" }] },
  "新子安": { nameKana: "しんこやす", interchanges: [{ toOperator: "京急", toLine: "本線", toStationName: "京急新子安" }] },
  "東神奈川": { nameKana: "ひがしかながわ", interchanges: [{ toOperator: "京急", toLine: "本線", toStationName: "京急東神奈川" }] },
  "横浜": { nameKana: "よこはま", interchanges: [{ toOperator: "東急", toLine: "東横線" }, { toOperator: "京急", toLine: "本線" }, { toOperator: "相鉄", toLine: "本線" }, { toOperator: "横浜市営地下鉄", toLine: "ブルーライン" }, { toOperator: "みなとみらい線", toLine: "みなとみらい線" }] },
  "桜木町": { nameKana: "さくらぎちょう", interchanges: [{ toOperator: "横浜市営地下鉄", toLine: "ブルーライン" }] },
  "関内": { nameKana: "かんない", interchanges: [{ toOperator: "横浜市営地下鉄", toLine: "ブルーライン" }] },
  "石川町": { nameKana: "いしかわちょう" },
  "山手": { nameKana: "やまて" },
  "根岸": { nameKana: "ねぎし" },
  "磯子": { nameKana: "いそご" },
  "新杉田": { nameKana: "しんすぎた", interchanges: [{ toOperator: "横浜シーサイドライン", toLine: "金沢シーサイドライン" }] },
  "洋光台": { nameKana: "ようこうだい" },
  "港南台": { nameKana: "こうなんだい" },
  "本郷台": { nameKana: "ほんごうだい" },
  "戸塚": { nameKana: "とつか", interchanges: [{ toOperator: "横浜市営地下鉄", toLine: "ブルーライン" }] },
  "大船": { nameKana: "おおふな", interchanges: [{ toOperator: "湘南モノレール", toLine: "江の島線" }] },
  "藤沢": { nameKana: "ふじさわ", interchanges: [{ toOperator: "小田急", toLine: "江ノ島線" }, { toOperator: "江ノ島電鉄", toLine: "江ノ島電鉄線" }] },
  "辻堂": { nameKana: "つじどう" },
  "茅ケ崎": { nameKana: "ちがさき" },
  "平塚": { nameKana: "ひらつか" },
  "大磯": { nameKana: "おおいそ" },
  "二宮": { nameKana: "にのみや" },
  "国府津": { nameKana: "こうづ" },
  "鴨宮": { nameKana: "かものみや" },
  "小田原": { nameKana: "おだわら", interchanges: [{ toOperator: "小田急", toLine: "小田原線" }, { toOperator: "箱根登山鉄道", toLine: "鉄道線" }, { toOperator: "伊豆箱根鉄道", toLine: "大雄山線" }] },
  "早川": { nameKana: "はやかわ" },
  "根府川": { nameKana: "ねぶかわ" },
  "真鶴": { nameKana: "まなづる" },
  "湯河原": { nameKana: "ゆがわら" },
  "熱海": { nameKana: "あたみ" },
  "西大井": { nameKana: "にしおおい" },
  "武蔵小杉": { nameKana: "むさしこすぎ", interchanges: [{ toOperator: "東急", toLine: "東横線" }, { toOperator: "東急", toLine: "目黒線" }] },
  "新川崎": { nameKana: "しんかわさき" },
  "保土ケ谷": { nameKana: "ほどがや" },
  "東戸塚": { nameKana: "ひがしとつか" },
  "北鎌倉": { nameKana: "きたかまくら" },
  "鎌倉": { nameKana: "かまくら", interchanges: [{ toOperator: "江ノ島電鉄", toLine: "江ノ島電鉄線" }] },
  "逗子": { nameKana: "ずし", interchanges: [{ toOperator: "京急", toLine: "逗子線", toStationName: "逗子・葉山" }] },
  "東逗子": { nameKana: "ひがしずし" },
  "田浦": { nameKana: "たうら" },
  "横須賀": { nameKana: "よこすか" },
  "衣笠": { nameKana: "きぬがさ" },
  "久里浜": { nameKana: "くりはま" },
  "尻手": { nameKana: "しって" },
  "矢向": { nameKana: "やこう" },
  "鹿島田": { nameKana: "かしまだ" },
  "平間": { nameKana: "ひらま" },
  "向河原": { nameKana: "むかいがわら" },
  "武蔵中原": { nameKana: "むさしなかはら" },
  "武蔵新城": { nameKana: "むさししんじょう" },
  "武蔵溝ノ口": { nameKana: "むさしみぞのくち", interchanges: [{ toOperator: "東急", toLine: "田園都市線", toStationName: "溝の口" }, { toOperator: "東急", toLine: "大井町線", toStationName: "溝の口" }] },
  "津田山": { nameKana: "つだやま" },
  "久地": { nameKana: "くじ" },
  "宿河原": { nameKana: "しゅくがわら" },
  "登戸": { nameKana: "のぼりと", interchanges: [{ toOperator: "小田急", toLine: "小田原線" }] },
  "中野島": { nameKana: "なかのしま" },
  "稲田堤": { nameKana: "いなだづつみ", interchanges: [{ toOperator: "京王", toLine: "相模原線", toStationName: "京王稲田堤" }] },
  "矢野口": { nameKana: "やのくち" },
  "稲城長沼": { nameKana: "いなぎながぬま" },
  "南多摩": { nameKana: "みなみたま" },
  "府中本町": { nameKana: "ふちゅうほんまち" },
  "分倍河原": { nameKana: "ぶばいがわら", interchanges: [{ toOperator: "京王", toLine: "京王線" }] },
  "西府": { nameKana: "にしふ" },
  "谷保": { nameKana: "やほ" },
  "矢川": { nameKana: "やがわ" },
  "西国立": { nameKana: "にしくにたち" },
  "立川": { nameKana: "たちかわ", interchanges: [{ toOperator: "多摩都市モノレール", toLine: "多摩都市モノレール線" }] },
  "大口": { nameKana: "おおぐち" },
  "菊名": { nameKana: "きくな", interchanges: [{ toOperator: "東急", toLine: "東横線" }] },
  "新横浜": { nameKana: "しんよこはま", interchanges: [{ toOperator: "横浜市営地下鉄", toLine: "ブルーライン" }, { toOperator: "相鉄", toLine: "相鉄新横浜線" }, { toOperator: "東急", toLine: "新横浜線" }] },
  "小机": { nameKana: "こづくえ" },
  "鴨居": { nameKana: "かもい" },
  "中山": { nameKana: "なかやま", interchanges: [{ toOperator: "横浜市営地下鉄", toLine: "グリーンライン" }] },
  "十日市場": { nameKana: "とおかいちば" },
  "長津田": { nameKana: "ながつた", interchanges: [{ toOperator: "東急", toLine: "田園都市線" }, { toOperator: "東急", toLine: "こどもの国線" }] },
  "成瀬": { nameKana: "なるせ" },
  "町田": { nameKana: "まちだ", interchanges: [{ toOperator: "小田急", toLine: "小田原線" }] },
  "古淵": { nameKana: "こぶち" },
  "淵野辺": { nameKana: "ふちのべ" },
  "矢部": { nameKana: "やべ" },
  "相模原": { nameKana: "さがみはら" },
  "橋本": { nameKana: "はしもと", interchanges: [{ toOperator: "京王", toLine: "相模原線" }] },
  "相原": { nameKana: "あいはら" },
  "八王子みなみ野": { nameKana: "はちおうじみなみの" },
  "片倉": { nameKana: "かたくら" },
  "八王子": { nameKana: "はちおうじ", interchanges: [{ toOperator: "京王", toLine: "京王線", toStationName: "京王八王子" }] },
  "来宮": { nameKana: "きのみや" },
  "伊豆多賀": { nameKana: "いずたが" },
  "網代": { nameKana: "あじろ" },
  "宇佐美": { nameKana: "うさみ" },
  "伊東": { nameKana: "いとう" },
  "北茅ケ崎": { nameKana: "きたちがさき" },
  "香川": { nameKana: "かがわ" },
  "寒川": { nameKana: "さむかわ" },
  "宮山": { nameKana: "みややま" },
  "倉見": { nameKana: "くらみ" },
  "門沢橋": { nameKana: "かどさわばし" },
  "社家": { nameKana: "しゃけ" },
  "厚木": { nameKana: "あつぎ", interchanges: [{ toOperator: "小田急", toLine: "小田原線" }] },
  "海老名": { nameKana: "えびな", interchanges: [{ toOperator: "小田急", toLine: "小田原線" }, { toOperator: "相鉄", toLine: "本線" }] },
  "入谷": { nameKana: "いりや" },
  "相武台下": { nameKana: "そうぶだいした" },
  "下溝": { nameKana: "しもみぞ" },
  "原当麻": { nameKana: "はらたいま" },
  "番田": { nameKana: "ばんだ" },
  "上溝": { nameKana: "かみみぞ" },
  "南橋本": { nameKana: "みなみはしもと" },
  "国道": { nameKana: "こくどう" },
  "鶴見小野": { nameKana: "つるみおの" },
  "弁天橋": { nameKana: "べんてんばし" },
  "浅野": { nameKana: "あさの" },
  "安善": { nameKana: "あんぜん" },
  "武蔵白石": { nameKana: "むさししらいし" },
  "浜川崎": { nameKana: "はまかわさき" },
  "昭和": { nameKana: "しょうわ" },
  "扇町": { nameKana: "おうぎまち" },
  "新芝浦": { nameKana: "しんしばうら" },
  "海芝浦": { nameKana: "うみしばうら" },
  "大川": { nameKana: "おおかわ" },
  "高崎": { nameKana: "たかさき", interchanges: [{ toOperator: "上信電鉄", toLine: "上信線" }] }
});
