// 路線別メタデータ: 京浜東北線（関東）
window.stationMetadataChunks = window.stationMetadataChunks || {};
window.railwayLineFileChunks = window.railwayLineFileChunks || {};
Object.assign(window.stationMetadataChunks, {
  "大宮": {"nameKana":"おおみや","interchanges":[{"toOperator":"東武","toLine":"野田線"},{"toOperator":"埼玉新都市交通","toLine":"伊奈線"}]},
  "さいたま新都心": {"nameKana":"さいたましんとしん"},
  "与野": {"nameKana":"よの"},
  "北浦和": {"nameKana":"きたうらわ"},
  "浦和": {"nameKana":"うらわ"},
  "南浦和": {"nameKana":"みなみうらわ"},
  "蕨": {"nameKana":"わらび"},
  "西川口": {"nameKana":"にしかわぐち"},
  "川口": {"nameKana":"かわぐち"},
  "赤羽": {"nameKana":"あかばね"},
  "東十条": {"nameKana":"ひがしじゅうじょう"},
  "王子": {"nameKana":"おうじ","interchanges":[{"toOperator":"東京メトロ","toLine":"南北線"},{"toOperator":"都電","toLine":"荒川線","toStationName":"王子駅前"}]},
  "上中里": {"nameKana":"かみなかざと"},
  "田端": {"nameKana":"たばた"},
  "西日暮里": {"nameKana":"にしにっぽり","interchanges":[{"toOperator":"東京メトロ","toLine":"千代田線"}]},
  "日暮里": {"nameKana":"にっぽり","interchanges":[{"toOperator":"京成","toLine":"本線"}]},
  "鶯谷": {"nameKana":"うぐいすだに"},
  "上野": {"nameKana":"うえの","interchanges":[{"toOperator":"東京メトロ","toLine":"銀座線"},{"toOperator":"東京メトロ","toLine":"日比谷線"}]},
  "御徒町": {"nameKana":"おかちまち","interchanges":[{"toOperator":"東京メトロ","toLine":"日比谷線","toStationName":"仲御徒町"}]},
  "秋葉原": {"nameKana":"あきはばら","interchanges":[{"toOperator":"東京メトロ","toLine":"日比谷線"},{"toOperator":"つくばエクスプレス","toLine":"常磐新線"}]},
  "神田": {"nameKana":"かんだ","interchanges":[{"toOperator":"東京メトロ","toLine":"銀座線"}]},
  "東京": {"nameKana":"とうきょう","interchanges":[{"toOperator":"東京メトロ","toLine":"丸ノ内線"}]},
  "有楽町": {"nameKana":"ゆうらくちょう","interchanges":[{"toOperator":"東京メトロ","toLine":"有楽町線"}]},
  "新橋": {"nameKana":"しんばし","interchanges":[{"toOperator":"都営","toLine":"浅草線"},{"toOperator":"東京メトロ","toLine":"銀座線"},{"toOperator":"ゆりかもめ","toLine":"東京臨海新交通臨海線"}]},
  "浜松町": {"nameKana":"はままつちょう","interchanges":[{"toOperator":"東京モノレール","toLine":"東京モノレール羽田空港線"},{"toOperator":"都営","toLine":"大江戸線","toStationName":"大門"},{"toOperator":"都営","toLine":"浅草線","toStationName":"大門"}]},
  "田町": {"nameKana":"たまち","interchanges":[{"toOperator":"都営","toLine":"浅草線","toStationName":"三田"},{"toOperator":"都営","toLine":"三田線","toStationName":"三田"}]},
  "高輪ゲートウェイ": {"nameKana":"たかなわげーとうぇい"},
  "品川": {"nameKana":"しながわ","interchanges":[{"toOperator":"京急","toLine":"本線"}]},
  "大井町": {"nameKana":"おおいまち","interchanges":[{"toOperator":"東急","toLine":"大井町線"},{"toOperator":"東京臨海高速鉄道","toLine":"りんかい線"}]},
  "大森": {"nameKana":"おおもり"},
  "蒲田": {"nameKana":"かまた","interchanges":[{"toOperator":"東急","toLine":"池上線"},{"toOperator":"東急","toLine":"多摩川線"}]},
  "川崎": {"nameKana":"かわさき","interchanges":[{"toOperator":"京急","toLine":"本線","toStationName":"京急川崎"}]},
  "鶴見": {"nameKana":"つるみ","interchanges":[{"toOperator":"京急","toLine":"本線","toStationName":"京急鶴見"}]},
  "新子安": {"nameKana":"しんこやす","interchanges":[{"toOperator":"京急","toLine":"本線","toStationName":"京急新子安"}]},
  "東神奈川": {"nameKana":"ひがしかながわ","interchanges":[{"toOperator":"京急","toLine":"本線","toStationName":"京急東神奈川"}]},
  "横浜": {"nameKana":"よこはま","interchanges":[{"toOperator":"東急","toLine":"東横線"},{"toOperator":"京急","toLine":"本線"},{"toOperator":"相鉄","toLine":"本線"},{"toOperator":"横浜市営地下鉄","toLine":"ブルーライン"},{"toOperator":"みなとみらい線","toLine":"みなとみらい線"}]},
  "桜木町": {"nameKana":"さくらぎちょう","interchanges":[{"toOperator":"横浜市営地下鉄","toLine":"ブルーライン"}]},
  "関内": {"nameKana":"かんない","interchanges":[{"toOperator":"横浜市営地下鉄","toLine":"ブルーライン"}]},
  "石川町": {"nameKana":"いしかわちょう"},
  "山手": {"nameKana":"やまて"},
  "根岸": {"nameKana":"ねぎし"},
  "磯子": {"nameKana":"いそご"},
  "新杉田": {"nameKana":"しんすぎた","interchanges":[{"toOperator":"横浜シーサイドライン","toLine":"金沢シーサイドライン"}]},
  "洋光台": {"nameKana":"ようこうだい"},
  "港南台": {"nameKana":"こうなんだい"},
  "本郷台": {"nameKana":"ほんごうだい"},
  "大船": {"nameKana":"おおふな","interchanges":[{"toOperator":"湘南モノレール","toLine":"江の島線"}]}
});

Object.assign(window.railwayLineFileChunks, {
  "kanto:keihin_tohoku_local": {
    area: "関東",
    operator: "JR東日本",
    lineName: "京浜東北線",
    lineNameKana: "けいひんとうほくせん",
    scope: "東京支社",
    routeSymbol: "JK",
    directionGroups: ["東海道方面", "東北・高崎方面"],
    stations: [
      { name: "大宮" }, { name: "さいたま新都心" }, { name: "与野" }, { name: "北浦和" }, { name: "浦和" },
      { name: "南浦和" }, { name: "蕨" }, { name: "西川口" }, { name: "川口" }, { name: "赤羽" },
      { name: "東十条" }, { name: "王子" }, { name: "上中里" }, { name: "田端" }, { name: "西日暮里" },
      { name: "日暮里" }, { name: "鶯谷" }, { name: "上野" }, { name: "御徒町" }, { name: "秋葉原" },
      { name: "神田" }, { name: "東京" }, { name: "有楽町" }, { name: "新橋" }, { name: "浜松町" },
      { name: "田町" }, { name: "高輪ゲートウェイ" }, { name: "品川" }, { name: "大井町" }, { name: "大森" },
      { name: "蒲田" }, { name: "川崎" }, { name: "鶴見" }, { name: "新子安" }, { name: "東神奈川" },
      { name: "横浜" }, { name: "桜木町" }, { name: "関内" }, { name: "石川町" }, { name: "山手" },
      { name: "根岸" }, { name: "磯子" }, { name: "新杉田" }, { name: "洋光台" }, { name: "港南台" },
      { name: "本郷台" }, { name: "大船" }
    ]
  }
});
