// 路線別メタデータ: 飯山線（信越/長野支社）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "豊野": {"nameKana":"とよの","interchanges":[{"toOperator":"JR東日本","toLine":"信越本線"}]},
  "信濃浅野": {"nameKana":"しなのあさの"},
  "立ケ花": {"nameKana":"たてがはな"},
  "上今井": {"nameKana":"かみいまい"},
  "替佐": {"nameKana":"かえさ"},
  "蓮": {"nameKana":"はちす"},
  "飯山": {"nameKana":"いいやま","interchanges":[{"toOperator":"JR東日本","toLine":"北陸新幹線"}]},
  "北飯山": {"nameKana":"きたいいやま"},
  "信濃平": {"nameKana":"しなのたいら"},
  "戸狩野沢温泉": {"nameKana":"とがりのざわおんせん"},
  "上境": {"nameKana":"かみさかい"},
  "上桑名川": {"nameKana":"かみくわながわ"},
  "桑名川": {"nameKana":"くわながわ"},
  "西大滝": {"nameKana":"にしおおたき"},
  "森宮野原": {"nameKana":"もりみやのはら"},
  "足滝": {"nameKana":"あしたき"},
  "越後田中": {"nameKana":"えちごたなか"},
  "津南": {"nameKana":"つなん"},
  "越後鹿渡": {"nameKana":"えちごしかわたり"},
  "越後田沢": {"nameKana":"えちごたざわ"},
  "越後水沢": {"nameKana":"えちごみずさわ"},
  "土市": {"nameKana":"どいち"},
  "十日町": {"nameKana":"とおかまち","interchanges":[{"toOperator":"北越急行","toLine":"ほくほく線"}]},
  "魚沼中条": {"nameKana":"うおぬまなかじょう"},
  "下条": {"nameKana":"しもじょう"},
  "越後岩沢": {"nameKana":"えちごいわさわ"},
  "内ケ巻": {"nameKana":"うちがまき"},
  "越後川口": {"nameKana":"えちごかわぐち","interchanges":[{"toOperator":"JR東日本","toLine":"上越線"}]},
});
