// 路線別メタデータ: 越後線（信越/新潟支社）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "柏崎": {"nameKana":"かしわざき","interchanges":[{"toOperator":"JR東日本","toLine":"信越本線"}]},
  "東柏崎": {"nameKana":"ひがしかしわざき"},
  "西中通": {"nameKana":"にしなかどおり"},
  "荒浜": {"nameKana":"あらはま"},
  "刈羽": {"nameKana":"かりわ"},
  "西山": {"nameKana":"にしやま"},
  "礼拝": {"nameKana":"らいはい"},
  "石地": {"nameKana":"いしじ"},
  "小木ノ城": {"nameKana":"おぎのじょう"},
  "出雲崎": {"nameKana":"いずもざき"},
  "妙法寺": {"nameKana":"みょうほうじ"},
  "小島谷": {"nameKana":"こじまや"},
  "桐原": {"nameKana":"きりはら"},
  "寺泊": {"nameKana":"てらどまり"},
  "分水": {"nameKana":"ぶんすい"},
  "粟生津": {"nameKana":"あおうづ"},
  "南吉田": {"nameKana":"みなみよしだ"},
  "吉田": {"nameKana":"よしだ","interchanges":[{"toOperator":"JR東日本","toLine":"弥彦線"}]},
  "北吉田": {"nameKana":"きたよしだ"},
  "岩室": {"nameKana":"いわむろ"},
  "巻": {"nameKana":"まき"},
  "越後曽根": {"nameKana":"えちごそね"},
  "越後赤塚": {"nameKana":"えちごあかつか"},
  "内野西が丘": {"nameKana":"うちのにしがおか"},
  "内野": {"nameKana":"うちの"},
  "新潟大学前": {"nameKana":"にいがただいがくまえ"},
  "寺尾": {"nameKana":"てらお"},
  "小針": {"nameKana":"こばり"},
  "青山": {"nameKana":"あおやま"},
  "関屋": {"nameKana":"せきや"},
  "白山": {"nameKana":"はくさん"},
  "新潟": {"nameKana":"にいがた","interchanges":[{"toOperator":"JR東日本","toLine":"信越本線"},{"toOperator":"JR東日本","toLine":"白新線"},{"toOperator":"JR東日本","toLine":"羽越本線"},{"toOperator":"JR東日本","toLine":"上越新幹線"}]},
});
