// 路線別メタデータ: 小海線（信越/長野支社）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "小淵沢": {"nameKana":"こぶちざわ","interchanges":[{"toOperator":"JR東日本","toLine":"中央本線"}]},
  "甲斐小泉": {"nameKana":"かいこいずみ"},
  "甲斐大泉": {"nameKana":"かいおおいずみ"},
  "清里": {"nameKana":"きよさと"},
  "野辺山": {"nameKana":"のべやま"},
  "信濃川上": {"nameKana":"しなのかわかみ"},
  "佐久広瀬": {"nameKana":"さくひろせ"},
  "佐久海ノ口": {"nameKana":"さくうみのくち"},
  "海尻": {"nameKana":"うみじり"},
  "松原湖": {"nameKana":"まつばらこ"},
  "小海": {"nameKana":"こうみ"},
  "馬流": {"nameKana":"まながし"},
  "高岩": {"nameKana":"たかいわ"},
  "八千穂": {"nameKana":"やちほ"},
  "海瀬": {"nameKana":"かいぜ"},
  "羽黒下": {"nameKana":"はぐろした"},
  "青沼": {"nameKana":"あおぬま"},
  "臼田": {"nameKana":"うすだ"},
  "龍岡城": {"nameKana":"たつおかじょう"},
  "太田部": {"nameKana":"おおたべ"},
  "中込": {"nameKana":"なかごみ"},
  "滑津": {"nameKana":"なめづ"},
  "北中込": {"nameKana":"きたなかごみ"},
  "岩村田": {"nameKana":"いわむらだ"},
  "佐久平": {"nameKana":"さくだいら","interchanges":[{"toOperator":"JR東日本","toLine":"北陸新幹線"}]},
  "中佐都": {"nameKana":"なかさと"},
  "美里": {"nameKana":"みさと"},
  "三岡": {"nameKana":"みつおか"},
  "乙女": {"nameKana":"おとめ"},
  "東小諸": {"nameKana":"ひがしこもろ"},
  "小諸": {"nameKana":"こもろ","interchanges":[{"toOperator":"しなの鉄道","toLine":"しなの鉄道線"}]},
});
