// 路線別メタデータ: 大糸線（信越/長野支社）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "松本": {"nameKana":"まつもと","interchanges":[{"toOperator":"JR東日本","toLine":"篠ノ井線"}]},
  "北松本": {"nameKana":"きたまつもと"},
  "島内": {"nameKana":"しまうち"},
  "島高松": {"nameKana":"しまたかまつ"},
  "梓橋": {"nameKana":"あずさばし"},
  "一日市場": {"nameKana":"ひといちば"},
  "中萱": {"nameKana":"なかがや"},
  "南豊科": {"nameKana":"みなみとよしな"},
  "豊科": {"nameKana":"とよしな"},
  "柏矢町": {"nameKana":"はくやちょう"},
  "穂高": {"nameKana":"ほたか"},
  "有明": {"nameKana":"ありあけ"},
  "安曇追分": {"nameKana":"あずみおいわけ"},
  "細野": {"nameKana":"ほその"},
  "北細野": {"nameKana":"きたほその"},
  "信濃松川": {"nameKana":"しなのまつかわ"},
  "安曇沓掛": {"nameKana":"あずみくつかけ"},
  "信濃常盤": {"nameKana":"しなのときわ"},
  "南大町": {"nameKana":"みなみおおまち"},
  "信濃大町": {"nameKana":"しなのおおまち"},
  "北大町": {"nameKana":"きたおおまち"},
  "白馬": {"nameKana":"はくば"},
  "南小谷": {"nameKana":"みなみおたり","interchanges":[{"toOperator":"JR西日本","toLine":"大糸線（糸魚川方面）"}]},
});
