// 路線別メタデータ: 仙石線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "あおば通": {"nameKana":"あおばどおり","interchanges":[{"toOperator":"仙台市地下鉄","toLine":"南北線・東西線","toStationName":"仙台駅接続"}]},
  "仙台": {"nameKana":"せんだい","interchanges":[{"toOperator":"JR東日本","toLine":"東北新幹線"},{"toOperator":"JR東日本","toLine":"東北本線"},{"toOperator":"JR東日本","toLine":"仙山線"},{"toOperator":"JR東日本","toLine":"常磐線"}]},
  "榴ケ岡": {"nameKana":"つつじがおか"},
  "宮城野原": {"nameKana":"みやぎのはら"},
  "陸前原ノ町": {"nameKana":"りくぜんはらのまち"},
  "苦竹": {"nameKana":"にがたけ"},
  "小鶴新田": {"nameKana":"こづるしんでん"},
  "福田町": {"nameKana":"ふくだまち"},
  "陸前高砂": {"nameKana":"りくぜんたかさご"},
  "中野栄": {"nameKana":"なかのさかえ"},
  "多賀城": {"nameKana":"たがじょう"},
  "下馬": {"nameKana":"げば"},
  "西塩釜": {"nameKana":"にししおがま"},
  "本塩釜": {"nameKana":"ほんしおがま"},
  "東塩釜": {"nameKana":"ひがししおがま"},
  "陸前浜田": {"nameKana":"りくぜんはまだ"},
  "松島海岸": {"nameKana":"まつしまかいがん"},
  "高城町": {"nameKana":"たかぎまち"},
  "手樽": {"nameKana":"てたる"},
  "陸前富山": {"nameKana":"りくぜんとみやま"},
  "陸前大塚": {"nameKana":"りくぜんおおつか"},
  "東名": {"nameKana":"とうな"},
  "野蒜": {"nameKana":"のびる"},
  "陸前小野": {"nameKana":"りくぜんおの"},
  "鹿妻": {"nameKana":"かづま"},
  "矢本": {"nameKana":"やもと"},
  "東矢本": {"nameKana":"ひがしやもと"},
  "陸前赤井": {"nameKana":"りくぜんあかい"},
  "蛇田": {"nameKana":"へびた"},
  "石巻": {"nameKana":"いしのまき","interchanges":[{"toOperator":"JR東日本","toLine":"石巻線"}]},
});
