// 路線別メタデータ: 磐越西線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "郡山": {"nameKana":"こおりやま","interchanges":[{"toOperator":"JR東日本","toLine":"東北新幹線"},{"toOperator":"JR東日本","toLine":"東北本線"},{"toOperator":"JR東日本","toLine":"磐越東線"}]},
  "郡山富田": {"nameKana":"こおりやまとみた"},
  "喜久田": {"nameKana":"きくた"},
  "安子ヶ島": {"nameKana":"あこがしま"},
  "磐梯熱海": {"nameKana":"ばんだいあたみ"},
  "中山宿": {"nameKana":"なかやまじゅく"},
  "上戸": {"nameKana":"じょうこ"},
  "猪苗代湖畔": {"nameKana":"いなわしろこはん"},
  "猪苗代": {"nameKana":"いなわしろ"},
  "川桁": {"nameKana":"かわげた"},
  "関都": {"nameKana":"せきと"},
  "磐梯町": {"nameKana":"ばんだいまち"},
  "東長原": {"nameKana":"ひがしながはら"},
  "広田": {"nameKana":"ひろた"},
  "会津若松": {"nameKana":"あいづわかまつ","interchanges":[{"toOperator":"JR東日本","toLine":"只見線"}]},
  "堂島": {"nameKana":"どうじま"},
  "笈川": {"nameKana":"おいかわ"},
  "塩川": {"nameKana":"しおかわ"},
  "姥堂": {"nameKana":"うばどう"},
  "会津豊川": {"nameKana":"あいづとよかわ"},
  "喜多方": {"nameKana":"きたかた"},
  "山都": {"nameKana":"やまと"},
  "荻野": {"nameKana":"おぎの"},
  "尾登": {"nameKana":"おのぼり"},
  "野沢": {"nameKana":"のざわ"},
});
