// 路線別メタデータ: 八戸線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "八戸": {"nameKana":"はちのへ","interchanges":[{"toOperator":"JR東日本","toLine":"東北新幹線"},{"toOperator":"青い森鉄道","toLine":"青い森鉄道線"}]},
  "長苗代": {"nameKana":"ながなわしろ"},
  "本八戸": {"nameKana":"ほんはちのへ"},
  "小中野": {"nameKana":"こなかの"},
  "陸奥湊": {"nameKana":"むつみなと"},
  "白銀": {"nameKana":"しろがね"},
  "鮫": {"nameKana":"さめ"},
  "陸奥白浜": {"nameKana":"むつしらはま"},
  "種差海岸": {"nameKana":"たねさしかいがん"},
  "大久喜": {"nameKana":"おおくき"},
  "金浜": {"nameKana":"かねはま"},
  "大蛇": {"nameKana":"おおじゃ"},
  "階上": {"nameKana":"はしかみ"},
  "角の浜": {"nameKana":"かどのはま"},
  "平内": {"nameKana":"ひらない"},
  "種市": {"nameKana":"たねいち"},
  "玉川": {"nameKana":"たまかわ"},
  "宿戸": {"nameKana":"しゅくのへ"},
  "陸中八木": {"nameKana":"りくちゅうやぎ"},
  "有家": {"nameKana":"うげ"},
  "陸中中野": {"nameKana":"りくちゅうなかの"},
  "侍浜": {"nameKana":"さむらいはま"},
  "陸中夏井": {"nameKana":"りくちゅうなつい"},
  "久慈": {"nameKana":"くじ","interchanges":[{"toOperator":"三陸鉄道","toLine":"リアス線"}]},
});
