// 路線別メタデータ: 花輪線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "大館": {"nameKana":"おおだて","interchanges":[{"toOperator":"JR東日本","toLine":"奥羽本線"}]},
  "東大館": {"nameKana":"ひがしおおだて"},
  "扇田": {"nameKana":"おうぎた"},
  "大滝温泉": {"nameKana":"おおたきおんせん"},
  "十二所": {"nameKana":"じゅうにしょ"},
  "沢尻": {"nameKana":"さわじり"},
  "土深井": {"nameKana":"どぶかい"},
  "末広": {"nameKana":"すえひろ"},
  "十和田南": {"nameKana":"とわだみなみ"},
  "柴平": {"nameKana":"しばひら"},
  "鹿角花輪": {"nameKana":"かづのはなわ"},
  "陸中大里": {"nameKana":"りくちゅうおおさと"},
  "八幡平": {"nameKana":"はちまんたい"},
  "湯瀬温泉": {"nameKana":"ゆぜおんせん"},
  "兄畑": {"nameKana":"あにはた"},
  "田山": {"nameKana":"たやま"},
  "横間": {"nameKana":"よこま"},
  "荒屋新町": {"nameKana":"あらやしんまち"},
  "小屋の畑": {"nameKana":"こやのはた"},
  "北森": {"nameKana":"きたもり"},
  "松尾八幡平": {"nameKana":"まつおはちまんたい"},
  "平館": {"nameKana":"ひらだて"},
  "大更": {"nameKana":"おおぶけ"},
  "東大更": {"nameKana":"ひがしおおぶけ"},
  "大釜": {"nameKana":"おおかま"},
  "小岩井": {"nameKana":"こいわい"},
  "好摩": {"nameKana":"こうま","interchanges":[{"toOperator":"JR東日本","toLine":"IGRいわて銀河鉄道線（直通運転あり）"}]},
});
