// 路線別メタデータ: 常磐線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "いわき": {"nameKana":"いわき","interchanges":[{"toOperator":"JR東日本","toLine":"磐越東線"}]},
  "草野": {"nameKana":"くさの"},
  "四ツ倉": {"nameKana":"よつくら"},
  "久ノ浜": {"nameKana":"ひさのはま"},
  "末続": {"nameKana":"すえつぎ"},
  "広野": {"nameKana":"ひろの"},
  "木戸": {"nameKana":"きど"},
  "竜田": {"nameKana":"たつた"},
  "富岡": {"nameKana":"とみおか"},
  "夜ノ森": {"nameKana":"よのもり"},
  "大野": {"nameKana":"おおの"},
  "双葉": {"nameKana":"ふたば"},
  "浪江": {"nameKana":"なみえ"},
  "小高": {"nameKana":"おだか"},
  "原ノ町": {"nameKana":"はらのまち"},
  "鹿島": {"nameKana":"かしま"},
  "相馬": {"nameKana":"そうま"},
  "駒ケ嶺": {"nameKana":"こまがみね"},
  "新地": {"nameKana":"しんち"},
  "坂元": {"nameKana":"さかもと"},
  "山下": {"nameKana":"やました"},
  "浜吉田": {"nameKana":"はまよしだ"},
  "亘理": {"nameKana":"わたり"},
  "岩沼": {"nameKana":"いわぬま","interchanges":[{"toOperator":"JR東日本","toLine":"東北本線"}]},
  "名取": {"nameKana":"なとり","interchanges":[{"toOperator":"仙台空港鉄道","toLine":"仙台空港線"}]},
  "南仙台": {"nameKana":"みなみせんだい"},
  "長町": {"nameKana":"ながまち","interchanges":[{"toOperator":"仙台市地下鉄","toLine":"南北線"}]},
  "仙台": {"nameKana":"せんだい","interchanges":[{"toOperator":"JR東日本","toLine":"東北新幹線"},{"toOperator":"JR東日本","toLine":"東北本線"},{"toOperator":"JR東日本","toLine":"仙山線"},{"toOperator":"JR東日本","toLine":"仙石線"}]},
});
