// 路線別メタデータ: 只見線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "会津若松": {"nameKana":"あいづわかまつ","interchanges":[{"toOperator":"JR東日本","toLine":"磐越西線"}]},
  "七日町": {"nameKana":"なぬかまち","interchanges":[{"toOperator":"会津鉄道","toLine":"会津線"}]},
  "西若松": {"nameKana":"にしわかまつ","interchanges":[{"toOperator":"会津鉄道","toLine":"会津線"}]},
  "会津本郷": {"nameKana":"あいづほんごう"},
  "会津高田": {"nameKana":"あいづたかだ"},
  "根岸": {"nameKana":"ねぎし"},
  "新鶴": {"nameKana":"にいつる"},
  "若宮": {"nameKana":"わかみや"},
  "会津坂下": {"nameKana":"あいづばんげ"},
  "塔寺": {"nameKana":"とうでら"},
  "会津坂本": {"nameKana":"あいづさかもと"},
  "会津柳津": {"nameKana":"あいづやないづ"},
  "郷戸": {"nameKana":"ごうど"},
  "滝谷": {"nameKana":"たきや"},
  "会津檜原": {"nameKana":"あいづひのはら"},
  "会津西方": {"nameKana":"あいづにしかた"},
  "会津宮下": {"nameKana":"あいづみやした"},
  "早戸": {"nameKana":"はやと"},
  "会津水沼": {"nameKana":"あいづみずぬま"},
  "会津中川": {"nameKana":"あいづなかがわ"},
  "会津川口": {"nameKana":"あいづかわぐち"},
  "本名": {"nameKana":"ほんな"},
  "会津越川": {"nameKana":"あいづこすがわ"},
  "只見": {"nameKana":"ただみ"},
  "大白川": {"nameKana":"おおしらかわ"},
  "入広瀬": {"nameKana":"いりひろせ"},
  "上条": {"nameKana":"かみじょう"},
  "越後須原": {"nameKana":"えちごすはら"},
  "魚沼田中": {"nameKana":"うおぬまたなか"},
  "越後広瀬": {"nameKana":"えちごひろせ"},
  "藪神": {"nameKana":"やぶかみ"},
  "小出": {"nameKana":"こいで","interchanges":[{"toOperator":"JR東日本","toLine":"上越線"}]},
});
