// 路線別メタデータ: 陸羽東線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "小牛田": {"nameKana":"こごた","interchanges":[{"toOperator":"JR東日本","toLine":"東北本線"},{"toOperator":"JR東日本","toLine":"石巻線"}]},
  "北浦": {"nameKana":"きたうら"},
  "陸前谷地": {"nameKana":"りくぜんやち"},
  "古川": {"nameKana":"ふるかわ","interchanges":[{"toOperator":"JR東日本","toLine":"東北新幹線"}]},
  "塚目": {"nameKana":"つかのめ"},
  "西古川": {"nameKana":"にしふるかわ"},
  "東大崎": {"nameKana":"ひがしおおさき"},
  "西大崎": {"nameKana":"にしおおさき"},
  "有備館": {"nameKana":"ゆうびかん"},
  "上野目": {"nameKana":"うわのめ"},
  "池月": {"nameKana":"いけづき"},
  "川渡温泉": {"nameKana":"かわたびおんせん"},
  "鳴子御殿湯": {"nameKana":"なるこごてんゆ"},
  "鳴子温泉": {"nameKana":"なるこおんせん"},
  "中山平温泉": {"nameKana":"なかやまだいらおんせん"},
  "堺田": {"nameKana":"さかいだ"},
  "赤倉温泉": {"nameKana":"あかくらおんせん"},
  "立小路": {"nameKana":"たちこうじ"},
  "最上": {"nameKana":"もがみ"},
  "大堀": {"nameKana":"おおほり"},
  "鵜杉": {"nameKana":"うすぎ"},
  "瀬見温泉": {"nameKana":"せみおんせん"},
  "東長沢": {"nameKana":"ひがしながさわ"},
  "長沢": {"nameKana":"ながさわ"},
  "南新庄": {"nameKana":"みなみしんじょう"},
  "新庄": {"nameKana":"しんじょう","interchanges":[{"toOperator":"JR東日本","toLine":"奥羽本線"},{"toOperator":"JR東日本","toLine":"山形新幹線"},{"toOperator":"JR東日本","toLine":"陸羽西線"}]},
});
