// 路線別メタデータ: 米坂線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "米沢": {"nameKana":"よねざわ","interchanges":[{"toOperator":"JR東日本","toLine":"奥羽本線"},{"toOperator":"JR東日本","toLine":"山形新幹線"}]},
  "南米沢": {"nameKana":"みなみよねざわ"},
  "西米沢": {"nameKana":"にしよねざわ"},
  "成島": {"nameKana":"なるしま"},
  "中郡": {"nameKana":"ちゅうぐん"},
  "羽前小松": {"nameKana":"うぜんこまつ"},
  "犬川": {"nameKana":"いぬかわ"},
  "今泉": {"nameKana":"いまいずみ","interchanges":[{"toOperator":"山形鉄道","toLine":"フラワー長井線"}]},
  "萩生": {"nameKana":"はぎゅう"},
  "羽前椿": {"nameKana":"うぜんつばき"},
  "手ノ子": {"nameKana":"てのこ"},
  "羽前沼沢": {"nameKana":"うぜんぬまざわ"},
  "伊佐領": {"nameKana":"いさりょう"},
  "羽前松岡": {"nameKana":"うぜんまつおか"},
  "小国": {"nameKana":"おぐに"},
  "越後金丸": {"nameKana":"えちごかなまる"},
  "越後片貝": {"nameKana":"えちごかたかい"},
  "越後下関": {"nameKana":"えちごしもせき"},
  "越後大島": {"nameKana":"えちごおおしま"},
  "平林": {"nameKana":"ひらばやし"},
  "坂町": {"nameKana":"さかまち","interchanges":[{"toOperator":"JR東日本","toLine":"羽越本線"}]},
});
