// 路線別メタデータ: 釜石線（東北）
window.stationMetadataChunks = window.stationMetadataChunks || {};
Object.assign(window.stationMetadataChunks, {
  "花巻": {"nameKana":"はなまき","interchanges":[{"toOperator":"JR東日本","toLine":"東北本線"}]},
  "似内": {"nameKana":"にたない"},
  "新花巻": {"nameKana":"しんはなまき","interchanges":[{"toOperator":"JR東日本","toLine":"東北新幹線"}]},
  "小山田": {"nameKana":"おやまだ"},
  "土沢": {"nameKana":"つちざわ"},
  "晴山": {"nameKana":"はれやま"},
  "岩根橋": {"nameKana":"いわねばし"},
  "宮守": {"nameKana":"みやもり"},
  "柏木平": {"nameKana":"かしわぎだいら"},
  "鱒沢": {"nameKana":"ますざわ"},
  "荒谷前": {"nameKana":"あらやまえ"},
  "岩手二日町": {"nameKana":"いわてふつかまち"},
  "綾織": {"nameKana":"あやおり"},
  "遠野": {"nameKana":"とおの"},
  "青笹": {"nameKana":"あおざさ"},
  "岩手上郷": {"nameKana":"いわてかみごう"},
  "平倉": {"nameKana":"ひらくら"},
  "足ヶ瀬": {"nameKana":"あしがせ"},
  "上有住": {"nameKana":"かみありす"},
  "陸中大橋": {"nameKana":"りくちゅうおおはし"},
  "洞泉": {"nameKana":"どうせん"},
  "松倉": {"nameKana":"まつくら"},
  "小佐野": {"nameKana":"こさの"},
  "釜石": {"nameKana":"かまいし","interchanges":[{"toOperator":"三陸鉄道","toLine":"リアス線"}]},
});
